/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package easyDOS;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import keeptoo.Drag;

/**
 *
 * @author josel
 */
public class Home extends javax.swing.JFrame {
	//Biblioteca biblio = new Biblioteca();
	/**
	 * Creates new form easyBox
	 */
	public Home() {
		try {
			checkFileUser();
		} catch (IOException ex) {
			Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
		}
		initComponents(); //Inicializo el home
		//Establezco que inicie en el centro de la pantalla
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
		this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
		DisplayPanel.setVisible(false);
	}

	private void checkFileUser() throws IOException {
		String url = getClass().getClassLoader().getResource("./Juegos/").getPath();
		url = url + "default.txt";
		url = url.substring(1, url.length());
		try {
			File file = new File(url);
			file.createNewFile();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddJuego = new keeptoo.KButton();
        btnMisJuegos = new keeptoo.KButton();
        btnSalir = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        DisplayPanel = new javax.swing.JPanel();
        JScrollBilioteca = new javax.swing.JScrollPane();
        biblioteca1 = new easyDOS.Biblioteca();
        btnPreferencias1 = new keeptoo.KButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddJuego.setText("Añadir Juego");
        btnAddJuego.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddJuego.setkEndColor(new java.awt.Color(153, 0, 153));
        btnAddJuego.setkStartColor(new java.awt.Color(102, 204, 255));
        btnAddJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        btnMisJuegos.setText("Mis Juegos");
        btnMisJuegos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMisJuegos.setkEndColor(new java.awt.Color(153, 0, 153));
        btnMisJuegos.setkStartColor(new java.awt.Color(102, 204, 255));
        btnMisJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisJuegosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMisJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setkBackGroundColor(new java.awt.Color(255, 0, 153));
        btnSalir.setkEndColor(new java.awt.Color(255, 102, 102));
        btnSalir.setkHoverForeGround(new java.awt.Color(255, 0, 153));
        btnSalir.setkHoverStartColor(new java.awt.Color(255, 0, 153));
        btnSalir.setkSelectedColor(new java.awt.Color(255, 0, 153));
        btnSalir.setkStartColor(new java.awt.Color(102, 204, 255));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/easyBox.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 36, 110, 150));

        javax.swing.GroupLayout biblioteca1Layout = new javax.swing.GroupLayout(biblioteca1);
        biblioteca1.setLayout(biblioteca1Layout);
        biblioteca1Layout.setHorizontalGroup(
            biblioteca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        biblioteca1Layout.setVerticalGroup(
            biblioteca1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        JScrollBilioteca.setViewportView(biblioteca1);

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JScrollBilioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JScrollBilioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        getContentPane().add(DisplayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 730, 440));

        btnPreferencias1.setText("Preferencias");
        btnPreferencias1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPreferencias1.setkEndColor(new java.awt.Color(153, 0, 153));
        btnPreferencias1.setkStartColor(new java.awt.Color(102, 204, 255));
        btnPreferencias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreferencias1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreferencias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        background.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backgroundKeyPressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnAddJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJuegoActionPerformed
		// TODO add your handling code here:
		biblioteca1.removeAll();
		biblioteca1.repaint();
		biblioteca1.crearBiblioteca(); //Genero la biblioteca
		biblioteca1.setVisible(true);
		JScrollBilioteca.setVisible(true);
		DisplayPanel.setVisible(true);
	}//GEN-LAST:event_btnAddJuegoActionPerformed

	private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
		// TODO add your handling code here:
		System.exit(0);
	}//GEN-LAST:event_btnSalirActionPerformed

	private void btnMisJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisJuegosActionPerformed
		try {
			// TODO add your handling code here:
                                         
                        
			biblioteca1.removeAll(); //Elimino todos los elementos de la biblioteca (graficos)
			biblioteca1.repaint();
			biblioteca1.getMisJuegos();
			biblioteca1.setVisible(true);                        
			JScrollBilioteca.setVisible(true);
			DisplayPanel.setVisible(true);
		} catch (IOException ex) {
			Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
		}
	}//GEN-LAST:event_btnMisJuegosActionPerformed

	private void backgroundKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backgroundKeyPressed
		// TODO add your handling code here:
	}//GEN-LAST:event_backgroundKeyPressed

	private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
		// TODO add your handling code here:
		new Drag(background).moveWindow(evt);
	}//GEN-LAST:event_formMouseDragged

	private void biblioteca1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biblioteca1MousePressed
		// TODO add your handling code here:
	}//GEN-LAST:event_biblioteca1MousePressed

	private void btnPreferencias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreferencias1ActionPerformed
		// TODO add your handling code here:
            preferencias p = new preferencias();
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();                    
            p.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);               
            p.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            p.setVisible(true);
            
	}//GEN-LAST:event_btnPreferencias1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Home().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JScrollPane JScrollBilioteca;
    private javax.swing.JLabel background;
    private easyDOS.Biblioteca biblioteca1;
    private keeptoo.KButton btnAddJuego;
    private keeptoo.KButton btnMisJuegos;
    private keeptoo.KButton btnPreferencias1;
    private keeptoo.KButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
