/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package easyDOS;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author josel
 */
public class InfoJuego extends javax.swing.JFrame {
	Boolean play = false;
	Juego _juego = new Juego();
	/**
	 * Creates new form test
	 */
	public InfoJuego() {
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
		this.setLocation(dim.width / 4 - this.getSize().width / 4, dim.height / 4 - this.getSize().height / 4);
		initComponents();
	}
	public InfoJuego(Juego g, Boolean flag) {
		initComponents();
		ImageIcon icon = new ImageIcon(getClass().getResource(g.getImagen()));
		Caratula.setIcon(icon);
		TextCompany.setText(g.getCompania());
		TextDesarrollador.setText(g.getDesarrollador());
		TextNombre.setText(g.getNombre());
		TextDescripcion.append(g.getDescrip());

		if (flag) {
			btnPlay.setText("Jugar");
			btnPlay.setActionCommand("Play");
			play = true;
			_juego = g;
                        btnDelete.setVisible(true);
		} else {
			btnPlay.setText("Añadir a Mis Juegos");
			btnPlay.setActionCommand("Add");
			play = false;
                        btnDelete.setVisible(false);
		}
		if (g.getImagen().equals("/img/AddGameUnknown.png")) {
			btnPlay.setVisible(false);
			TextCompany.setEditable(true);
			TextDesarrollador.setEditable(true);
			TextDescripcion.setEditable(true);
			TextNombre.setEditable(true);
			btnPlay.setText("Añadir nuevo Juego");
			btnPlay.setActionCommand("AddNuevo");
			btnPlay.setVisible(true);
                        btnDelete.setVisible(false);
		}
	}




	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Caratula = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        LCompany = new javax.swing.JLabel();
        LDesarrollador = new javax.swing.JLabel();
        LDescripcion = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        TextCompany = new javax.swing.JTextField();
        TextDesarrollador = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextDescripcion = new javax.swing.JTextArea();
        btnPlay = new keeptoo.KButton();
        btnCancel = new keeptoo.KButton();
        btnDelete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Caratula.setPreferredSize(new java.awt.Dimension(150, 171));

        LNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LNombre.setText("Nombre: ");

        LCompany.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LCompany.setText("Compañia:");

        LDesarrollador.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LDesarrollador.setText("Desarrollador:");

        LDescripcion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LDescripcion.setText("Descripción");

        TextNombre.setEditable(false);
        TextNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TextCompany.setEditable(false);
        TextCompany.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TextDesarrollador.setEditable(false);
        TextDesarrollador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TextDescripcion.setColumns(20);
        TextDescripcion.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        TextDescripcion.setLineWrap(true);
        TextDescripcion.setRows(5);
        TextDescripcion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(TextDescripcion);

        btnPlay.setText("Jugar");
        btnPlay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-32.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDescripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LDesarrollador)
                                    .addComponent(LCompany)
                                    .addComponent(LNombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextCompany)
                                    .addComponent(TextDesarrollador)
                                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Caratula, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnDelete)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNombre)
                            .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LCompany)
                            .addComponent(TextCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LDesarrollador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextDesarrollador))
                        .addGap(27, 27, 27)
                        .addComponent(LDescripcion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Caratula, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_kButton1ActionPerformed

	private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_kButton2ActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_btnCancelActionPerformed

	private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
		// TODO add your handling code here:
		String action = btnPlay.getText();
		switch (action) {
		case "Añadir nuevo Juego":
			AddJuego();
			break;
		case "Close":
			this.dispose();
		case "Jugar":
			break;
		case "Añadir a Mis Juegos":
			AddJuego();
			break;
		}
	}//GEN-LAST:event_btnPlayMouseClicked
	void AddJuego() {
		AddJuego frameJuego = new AddJuego();
		frameJuego.setVisible(true);
		frameJuego.setTitle("Añadir juego " + TextNombre.getText());
		frameJuego.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		frameJuego.addWindowListener(new WindowListener() {
			@Override
			public void windowClosed(WindowEvent e) {
				//Si se ha cerrado la ventana se comprueba el title
				if (!frameJuego.getTitle().equals("Error")) {
					//El juego se va a insertar
					
					String ruta = frameJuego.getTitle();
					String  fileDefault = getClass().getClassLoader().getResource("./Juegos/default.txt").getPath();

					btnPlay.setText("Finalizar Configuración");
					btnPlay.addActionListener(new ActionListener() {
						@Override
						public void actionPerformed(ActionEvent e) {
                                                    try (Writer output = new BufferedWriter(new FileWriter(fileDefault, true))) { 
                                                           String Nombre = TextNombre.getText();
                                                           String Desarrollador=TextDesarrollador.getText();
                                                           String Compania=TextCompany.getText();
                                                           String Descripcion=TextDescripcion.getText();
                                                           String imagen="/img/AddGameUnknown.png";
                                                           if(Nombre.equals("") || Nombre.isEmpty() || Nombre.equals(" ")
                                                                   ||Desarrollador.equals("") || Desarrollador.isEmpty() || Desarrollador.equals(" ")
                                                                   ||Compania.equals("") || Compania.isEmpty() || Compania.equals(" ")
                                                                   ||Descripcion.equals("") || Descripcion.isEmpty() || Descripcion.equals(" "))
                                                           {
                                                                //eL NOMBRE NO ESTA DEFINIDO
									TextNombre.setBackground(Color.red);
									TextNombre.setForeground(Color.white);
                                                                        TextDesarrollador.setBackground(Color.red);
									TextDesarrollador.setForeground(Color.white);
                                                                        TextCompany.setBackground(Color.red);
									TextCompany.setForeground(Color.white); 
                                                                        TextDescripcion.setBackground(Color.red);
									TextDescripcion.setForeground(Color.white); 
                                                           }
                                                           else
                                                           {
                                                                Juego j=new Juego(100,Nombre,Desarrollador,Compania,"Genero",Descripcion,imagen);
								output.append(Nombre + "," + ruta + "\n");
                                                                output.close();
                                                                rehacerBiblioteca(j);
                                                                finalizar();                                                           
                                                           }
                                                    } catch (IOException ex) {
                                                        Logger.getLogger(InfoJuego.class.getName()).log(Level.SEVERE, null, ex);
                                                    }                                                   
						}
					});


				}

			}
			//Funciones de ventana no usadas para nuestro problema
			@Override
			public void windowIconified(WindowEvent e) {}
			@Override
			public void windowOpened(WindowEvent e) {}
			@Override
			public void windowClosing(WindowEvent e) {}
			@Override
			public void windowDeiconified(WindowEvent e) {}
			@Override
			public void windowActivated(WindowEvent e) {}
			@Override
			public void windowDeactivated(WindowEvent e) {}
		});

	}
        
        private void rehacerBiblioteca(Juego j) throws FileNotFoundException, IOException
        {
            //TODO 1-LEer ficherusmenio de listado de juegos 2-Volvar al temporal 3-dflhjkasfdlhjk
            
            String file = getClass().getClassLoader().getResource("./Juegos/listado_juegos.txt").getPath();
            file = file.substring(1, file.length()); //Eliminamos la /inicial que encontramos al obtener la ruta
            FileReader f = new FileReader(file);
            BufferedReader b = new BufferedReader(f);
            String cadena;
            
            System.out.println(j.getUrl()+"dfas");
            
            //FICHERO AUXILIAR

            String url = getClass().getClassLoader().getResource("./Juegos/").getPath();
            url = url + "temp.txt";
            url = url.substring(1, url.length());

            File file2 = new File(url);
            file2.createNewFile();

            FileWriter fw = new FileWriter(file2);


                    while ((cadena = b.readLine()) != null) {
                  
                           fw.append(cadena+"\n");
                    }

                    fw.append(j.getNombre()+"\n");
                    fw.append(j.getCompania()+"\n");
                    fw.append(j.getDesarrollador()+"\n");
                    fw.append(j.getTipo()+"\n");
                    fw.append(j.getDescrip()+"\n");
                    fw.append(j.getUrl());
                    
                    b.close();
            fw.close();

            File antiguo = new File(file);
            antiguo.delete();

            File nuevo = new File(url);
            boolean success = nuevo.renameTo(antiguo);
        }
        
	private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
		// TODO add your handling code here:
		if (play) {
			try {
				String url = getClass().getClassLoader().getResource("./dosBOX/DOSBoxPortable.exe").getPath();
				url  = url + " " + _juego.getUrl();
				url = url.substring(1, url.length());
				url = url.replace("/", "\\");
				Runtime.getRuntime().exec(url);
				dispose();
			} catch (IOException ioe) {
				System.out.println (ioe);
			}
		}
	}//GEN-LAST:event_btnPlayActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
            
            String nombreJuego=TextNombre.getText();
            try {
                borrarJuego(nombreJuego);
            } catch (IOException ex) {
                Logger.getLogger(InfoJuego.class.getName()).log(Level.SEVERE, null, ex);
            }
        dispose();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void borrarJuego(String nombreJuego) throws FileNotFoundException, IOException
    {
        //FICHERO INICIAL
		String file = getClass().getClassLoader().getResource("./Juegos/default.txt").getPath();
		file = file.substring(1, file.length()); //Eliminamos la /inicial que encontramos al obtener la ruta
		FileReader f = new FileReader(file);
		BufferedReader b = new BufferedReader(f);
		String cadena;

		//FICHERO AUXILIAR

		String url = getClass().getClassLoader().getResource("./Juegos/").getPath();
		url = url + "temp.txt";
		url = url.substring(1, url.length());

		File file2 = new File(url);
		file2.createNewFile();

		FileWriter fw = new FileWriter(file2);

		String[] parts;
                
                while ((cadena = b.readLine()) != null) {
                   parts=cadena.split(",");
                   
                   if(!parts[0].equals(nombreJuego))
                   {
                       fw.append(cadena);
                   }
                   
                }
                
                b.close();
		fw.close();

		File antiguo = new File(file);
		antiguo.delete();

		File nuevo = new File(url);
		boolean success = nuevo.renameTo(antiguo);
                
    }
    
    private void finalizar() {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InfoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InfoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InfoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InfoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InfoJuego().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caratula;
    private javax.swing.JLabel LCompany;
    private javax.swing.JLabel LDesarrollador;
    private javax.swing.JLabel LDescripcion;
    private javax.swing.JLabel LNombre;
    private javax.swing.JTextField TextCompany;
    private javax.swing.JTextField TextDesarrollador;
    private javax.swing.JTextArea TextDescripcion;
    private javax.swing.JTextField TextNombre;
    private keeptoo.KButton btnCancel;
    private javax.swing.JLabel btnDelete;
    private keeptoo.KButton btnPlay;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}